version: "3.7"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  site-ui:
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env.ui
    container_name: ui
    image: zemuldo/site-ui
    labels:
      - com.centurylinklabs.watchtower.enable=true

  site-api:
    restart: always
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    env_file:
      - .env.api
    environment:
      - DB_HOST=mongo
    container_name: api
    image: zemuldo/site-api
    labels:
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ${MONGOD_DATA_PATH:-/var/lib/mongodb}:/data/db

    restart: always

  watchtower:
    image: v2tec/watchtower
    command: --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    restart: always
