version: "3.7"
services:
  site-ui:
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env.ui
    container_name: ui
    image: zemuldo/site-ui
    labels:
      - com.centurylinklabs.watchtower.enable=true

  site-api:
    restart: always
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    env_file:
      - .env.api
    environment:
      - DB_HOST=mongo
    container_name: api
    image: gcr.io/$GCP_PROJECT_ID/site-api
    labels:
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ${MONGOD_DATA_PATH:-/var/lib/mongodb}:/data/db

    restart: always

  watch:
    image: v2tec/watchtower
    command: --cleanup --label-enable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    restart: always
