---

apiVersion: v1
kind: Service
metadata:
  name: site-ui
  namespace: z-site
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: site
    targetPort: 3000
  selector:
    app: site-ui
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: site-ui
  name: site-ui
  namespace: z-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-ui
  template:
    metadata:
      labels:
        app: site-ui
    spec:
      containers:
      - image: zemuldo/site-ui:latest
        name: site-ui
        env:
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: site-secrets
                key: UI_PORT
          - name: API_URL
            valueFrom:
              secretKeyRef:
                name: site-secrets
                key: API_URL
          - name: UI_URL
            valueFrom:
              secretKeyRef:
                name: site-secrets
                key: UI_URL
          - name: UI_URL_DOMAIN
            valueFrom:
              secretKeyRef:
                name: site-secrets
                key: UI_URL_DOMAIN
          - name: Z_SITE_IMAGES_URL
            valueFrom:
              secretKeyRef:
                name: site-secrets
                key: Z_SITE_IMAGES_URL
          - name: GA_TRACKING_ID
            valueFrom:
              secretKeyRef:
                name: site-secrets
                key: GA_TRACKING_ID
        ports:
          - name: site-ui
            containerPort: 3000
        volumeMounts:
          - name: z-site-images
            mountPath: /usr/src/app/public/z-site-images
      volumes:
        - name: z-site-images
          nfs:
            server: 209.97.137.61
            path: /mnt/z-site-images
---