apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  namespace: z-site
  labels:
    name: mongo-headless
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongo

---

# stateful set config for mongo
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: z-site
spec:
  selector:
      matchLabels:
        role: mongo
        environment: production
  serviceName: "mongo-headless"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: production
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command: ["/bin/sh","-c"]
          args: ["echo LFppSYiLyGVNTIYVLqETTibR14XupZ9SWcg/eKc430PZfamWL59rbgorGUNdU9HC > mongo.key; chmod 600 mongo.key; mongod --replSet zemuldo --keyFile mongo.key --auth --bind_ip_all"]

          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-persistent-storage
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 3Gi
---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-backup
  name: mongo-backup
  namespace: z-site
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-backup
    spec:
      containers:
      - image: zemuldo/mongo-backup
        name: mongo-backup
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        env:
        - name: CRON_TIME
          value: "0 0 * * *"
        - name: MAX_BACKUPS
          value: "10"
        - name: INIT_BACKUP
          value: "yes"
        - name: MONGO_URI
          value: "mongodb://admin:E0P2O1m-JaAn2AMranJY-9CRSkq9ocfzVHMkdKD@mongo-0.mongo-headless.z-site.svc.cluster.local:27017,mongo-1.mongo-headless.z-site.svc.cluster.local:27017,mongo-2.mongo-headless.z-site.svc.cluster.local:27017/zemuldo-site?replicaSet=zemuldo"
        volumeMounts:
            - name: mongo-backup
              mountPath: /backup
      volumes:
        - name: mongo-backup
          nfs:
            server: 209.97.137.61
            path: /mnt/mongo-backup
---