apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-backup-pvc
  namespace: z-site
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-secondary-backup-pvc
  namespace: z-site
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---