version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ${MONGOD_DATA_PATH:-/var/lib/mongodb}:/data/db

    restart: always